# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Booker - Book Tracker' do
  use_frameworks!

  # Pods for Booker - Book Tracker
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RealmSwift'
  
end
