# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Booker - Book Tracker' do
  use_frameworks!

  # Pods for Booker - Book Tracker
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'RealmSwift'
  pod 'Charts'
  
end
